/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package inventorysystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yves0
 */
public class AddDialogue extends javax.swing.JDialog {

    /**
     * Creates new form AddDialogue
     */
    ConnectDB db;
    DefaultTableModel tblModel;

    public AddDialogue(java.awt.Frame parent, boolean modal, ConnectDB db, DefaultTableModel tblModel) {
        super(parent, modal);
        this.db = db;
        this.tblModel = (DefaultTableModel) tblModel;
        db.createItemTypeDatabase();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanelAdd = new javax.swing.JPanel();
        BottomPanelAdd = new javax.swing.JPanel();
        ButtonAddAdd = new javax.swing.JButton();
        ButtonCancelAdd = new javax.swing.JButton();
        CenterPanelAdd = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ItemNameLabel = new javax.swing.JLabel();
        ItemNameTextField = new javax.swing.JTextField();
        CostLabel = new javax.swing.JLabel();
        CostTextField = new javax.swing.JTextField();
        SellingLabel = new javax.swing.JLabel();
        SellingTextField = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityField = new javax.swing.JPanel();
        jButtonMinus = new javax.swing.JButton();
        QuantityText = new javax.swing.JTextField();
        jButtonPlus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ItemNameLabel1 = new javax.swing.JLabel();
        ItemNameLabel2 = new javax.swing.JLabel();
        TotalInventoryTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Item");
        setResizable(false);

        TopPanelAdd.setBackground(new java.awt.Color(0, 0, 102));
        TopPanelAdd.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout TopPanelAddLayout = new javax.swing.GroupLayout(TopPanelAdd);
        TopPanelAdd.setLayout(TopPanelAddLayout);
        TopPanelAddLayout.setHorizontalGroup(
            TopPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        TopPanelAddLayout.setVerticalGroup(
            TopPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        BottomPanelAdd.setBackground(new java.awt.Color(0, 0, 102));
        BottomPanelAdd.setPreferredSize(new java.awt.Dimension(50, 50));
        BottomPanelAdd.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 12));

        ButtonAddAdd.setText("Add");
        ButtonAddAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddAddActionPerformed(evt);
            }
        });
        BottomPanelAdd.add(ButtonAddAdd);

        ButtonCancelAdd.setText("Cancel");
        ButtonCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelAddActionPerformed(evt);
            }
        });
        BottomPanelAdd.add(ButtonCancelAdd);

        CenterPanelAdd.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        ItemNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemNameLabel.setText("Item Name");
        jPanel2.add(ItemNameLabel);

        ItemNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(ItemNameTextField);

        CostLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CostLabel.setText("Cost");
        jPanel2.add(CostLabel);

        CostTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CostTextFieldPropertyChange(evt);
            }
        });
        CostTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostTextFieldKeyTyped(evt);
            }
        });
        jPanel2.add(CostTextField);

        SellingLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SellingLabel.setText("Selling");
        jPanel2.add(SellingLabel);

        SellingTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SellingTextFieldKeyTyped(evt);
            }
        });
        jPanel2.add(SellingTextField);

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        QuantityLabel.setText("Quantity");
        jPanel2.add(QuantityLabel);

        QuantityField.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jButtonMinus.setText("-1");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        QuantityField.add(jButtonMinus);

        QuantityText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuantityText.setText("0");
        QuantityText.setPreferredSize(new java.awt.Dimension(95, 35));
        QuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityTextKeyTyped(evt);
            }
        });
        QuantityField.add(QuantityText);

        jButtonPlus.setText("+1");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        QuantityField.add(jButtonPlus);

        jPanel2.add(QuantityField);

        CenterPanelAdd.add(jPanel2);

        ItemNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemNameLabel1.setText("Item Type");

        ItemNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemNameLabel2.setText("Total Inventory");

        TotalInventoryTextField.setEnabled(false);
        TotalInventoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalInventoryTextFieldActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(db.itemData));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemNameLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemNameLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalInventoryTextField)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(ItemNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalInventoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        CenterPanelAdd.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TopPanelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CenterPanelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BottomPanelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TopPanelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(CenterPanelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(BottomPanelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddAddActionPerformed
        if (ItemNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(CenterPanelAdd, "Item name cannot be empty.", "Alert", JOptionPane.WARNING_MESSAGE);
        } //add exception for minimun string lenght
        else if (CostTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(CenterPanelAdd, "Cost cannot be empty.", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if (SellingTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(CenterPanelAdd, "Selling cannot be empty.", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if (QuantityText.getText().equals("")) {
            JOptionPane.showMessageDialog(CenterPanelAdd, "Quantity cannot be empty.", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if (jComboBox1.getSelectedItem().equals("Add type") || jComboBox1.getSelectedItem().equals("Select type")) {
            JOptionPane.showMessageDialog(CenterPanelAdd, "Item type cannot be empty.", "Alert", JOptionPane.WARNING_MESSAGE);
        } else {

            db.insertRowSql(ItemNameTextField.getText(), jComboBox1.getSelectedItem().toString(), Integer.valueOf(CostTextField.getText()),
                    Integer.valueOf(SellingTextField.getText()), Integer.valueOf(QuantityText.getText()), Integer.valueOf(SellingTextField.getText()) * Integer.valueOf(QuantityText.getText()));
            Object tbData[] = {db.getLastRowID(), ItemNameTextField.getText(), jComboBox1.getSelectedItem().toString(), Integer.valueOf(CostTextField.getText()),
                Integer.valueOf(SellingTextField.getText()), Integer.valueOf(QuantityText.getText()), Integer.valueOf(SellingTextField.getText()) * Integer.valueOf(QuantityText.getText())};
            tblModel.addRow(tbData);
            repaint();
            dispose();
        }
    }//GEN-LAST:event_ButtonAddAddActionPerformed

    private void ButtonCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelAddActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonCancelAddActionPerformed

    private void CostTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_CostTextFieldKeyTyped

    private void SellingTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SellingTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_SellingTextFieldKeyTyped

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        if (!QuantityText.getText().equals("")) {
            if (Integer.valueOf(QuantityText.getText()) != 0) {
                int number = Integer.valueOf(QuantityText.getText());
                number -= 1;
                QuantityText.setText(Integer.toString(number));
            }
        }
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void QuantityTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityTextKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_QuantityTextKeyTyped

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        if (!QuantityText.getText().equals("")) {
            int number = Integer.valueOf(QuantityText.getText());
            number += 1;
            QuantityText.setText(Integer.toString(number));
        }
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void TotalInventoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalInventoryTextFieldActionPerformed

    }//GEN-LAST:event_TotalInventoryTextFieldActionPerformed

    private void CostTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CostTextFieldPropertyChange

    }//GEN-LAST:event_CostTextFieldPropertyChange

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String s = (String) jComboBox1.getSelectedItem();
        try {
            if (s.equals("Add type")) {
                String m = JOptionPane.showInputDialog(null, "Enter item type name", "Item name", JOptionPane.INFORMATION_MESSAGE);
                if (m.equals("")) {
                    JOptionPane.showMessageDialog(CenterPanelAdd, "Item name cannot be empty.", "Alert", JOptionPane.WARNING_MESSAGE);
                } else {

                    db.insertRowItemType(m);
                    jComboBox1.removeAllItems();
                    db.createItemTypeDatabase();
                    jComboBox1.addItem("Select type");
                    for (int i = 1; i < db.getItemTypeRowCount()-2; i++) {
                        jComboBox1.addItem(db.itemData[i]);
                    }
                    jComboBox1.addItem("Add type");

                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanelAdd;
    private javax.swing.JButton ButtonAddAdd;
    private javax.swing.JButton ButtonCancelAdd;
    private javax.swing.JPanel CenterPanelAdd;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JTextField CostTextField;
    private javax.swing.JLabel ItemNameLabel;
    private javax.swing.JLabel ItemNameLabel1;
    private javax.swing.JLabel ItemNameLabel2;
    private javax.swing.JTextField ItemNameTextField;
    private javax.swing.JPanel QuantityField;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityText;
    private javax.swing.JLabel SellingLabel;
    private javax.swing.JTextField SellingTextField;
    private javax.swing.JPanel TopPanelAdd;
    private javax.swing.JTextField TotalInventoryTextField;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
