/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import javax.swing.JOptionPane;

/**
 *
 * @author yves0
 */
public class AddGUI extends javax.swing.JFrame {

    //ConnectDB db = new InventoryTable().db; 
    
    public AddGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TopPanel = new javax.swing.JPanel();
        BottomPanel = new javax.swing.JPanel();
        ButtonAdd = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        CenterPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ItemNameLabel = new javax.swing.JLabel();
        ItemNameTextField = new javax.swing.JTextField();
        CostLabel = new javax.swing.JLabel();
        CostTextField = new javax.swing.JTextField();
        SellingLabel = new javax.swing.JLabel();
        SellingTextField = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityField = new javax.swing.JPanel();
        jButtonMinus = new javax.swing.JButton();
        QuantityText = new javax.swing.JTextField();
        jButtonPlus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ItemNameLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        ItemNameLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Item");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        TopPanel.setBackground(new java.awt.Color(0, 0, 102));
        TopPanel.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(TopPanel, java.awt.BorderLayout.PAGE_START);

        BottomPanel.setBackground(new java.awt.Color(0, 0, 102));
        BottomPanel.setPreferredSize(new java.awt.Dimension(50, 50));
        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 12));

        ButtonAdd.setText("Add");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });
        BottomPanel.add(ButtonAdd);

        ButtonCancel.setText("Cancel");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });
        BottomPanel.add(ButtonCancel);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.PAGE_END);

        CenterPanel.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        ItemNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemNameLabel.setText("Item Name");
        jPanel1.add(ItemNameLabel);

        ItemNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(ItemNameTextField);

        CostLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CostLabel.setText("Cost");
        jPanel1.add(CostLabel);

        CostTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(CostTextField);

        SellingLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SellingLabel.setText("Selling");
        jPanel1.add(SellingLabel);

        SellingTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SellingTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(SellingTextField);

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        QuantityLabel.setText("Quantity");
        jPanel1.add(QuantityLabel);

        QuantityField.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jButtonMinus.setText("-1");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        QuantityField.add(jButtonMinus);

        QuantityText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuantityText.setPreferredSize(new java.awt.Dimension(95, 35));
        QuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityTextKeyTyped(evt);
            }
        });
        QuantityField.add(QuantityText);

        jButtonPlus.setText("+1");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        QuantityField.add(jButtonPlus);

        jPanel1.add(QuantityField);

        CenterPanel.add(jPanel1);

        ItemNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemNameLabel1.setText("Total Items");

        jTextField2.setEnabled(false);

        ItemNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemNameLabel2.setText("Total Inventory");

        jTextField3.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ItemNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ItemNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        CenterPanel.add(jPanel3);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        if(ItemNameTextField.getText().equals("")){
            JOptionPane.showMessageDialog(CenterPanel,"Item name cannot be empty.","Alert",JOptionPane.WARNING_MESSAGE);
        }
        //add exception for minimun string lenght
        else if(CostTextField.getText().equals("")){
            JOptionPane.showMessageDialog(CenterPanel,"Cost cannot be empty.","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else if(SellingTextField.getText().equals("")){
            JOptionPane.showMessageDialog(CenterPanel,"Selling cannot be empty.","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else if(QuantityText.getText().equals("")){
            JOptionPane.showMessageDialog(CenterPanel,"Quantity cannot be empty.","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            db.insertRowSql(ItemNameTextField.getText(), Integer.valueOf(CostTextField.getText())
            , Integer.valueOf(SellingTextField.getText()), Integer.valueOf(QuantityText.getText()), 0, 0);
            dispose();
        }
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        if (!QuantityText.getText().equals("")) {
            if (Integer.valueOf(QuantityText.getText()) != 0) {
                int number = Integer.valueOf(QuantityText.getText());
                number -= 1;
                QuantityText.setText(Integer.toString(number));
            }
        }
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        if (!QuantityText.getText().equals("")) {
            int number = Integer.valueOf(QuantityText.getText());
            number += 1;
            QuantityText.setText(Integer.toString(number));
        }
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void QuantityTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityTextKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_QuantityTextKeyTyped

    private void CostTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_CostTextFieldKeyTyped

    private void SellingTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SellingTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_SellingTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JTextField CostTextField;
    private javax.swing.JLabel ItemNameLabel;
    private javax.swing.JLabel ItemNameLabel1;
    private javax.swing.JLabel ItemNameLabel2;
    private javax.swing.JTextField ItemNameTextField;
    private javax.swing.JPanel QuantityField;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityText;
    private javax.swing.JLabel SellingLabel;
    private javax.swing.JTextField SellingTextField;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
