/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author yves0
 */
public class MainPageGUI extends javax.swing.JFrame {

    ConnectDB db = new InventorySystem().db;
    DefaultTableModel tblModel;

    public MainPageGUI() {
        initComponents();
        tblModel = (DefaultTableModel) InventoryTable.getModel();
        db.getSqlRows();
        setSum();
        //db.getItemTypeRows();
        //db.createItemTypeDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IconLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        InventoryTable = new javax.swing.JTable();
        BottomPanel = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        NumbersPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelSum = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTotalInventory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sumtech Inventory System");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 120));

        IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Res/IconSumtech.png"))); // NOI18N

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(IconLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        InventoryTable.setAutoCreateRowSorter(true);
        InventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            db.data,
            new String [] {
                "ID", "Name", "Type", "Cost", "Selling", "Quantity", "Total Inventory"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.Integer.class,
                java.lang.Integer.class,
                java.lang.Integer.class,
                java.lang.Integer.class,
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InventoryTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        InventoryTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(InventoryTable);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        BottomPanel.setBackground(new java.awt.Color(0, 0, 102));
        BottomPanel.setName("BottomPanel"); // NOI18N
        BottomPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        ButtonPanel.setBackground(new java.awt.Color(0, 0, 102));

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButtonAdd);

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButtonUpdate);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButtonDelete);

        NumbersPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        NumbersPanel.setPreferredSize(new java.awt.Dimension(201, 100));
        NumbersPanel.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Overall Total Inventory:   ");
        NumbersPanel.add(jLabel2);

        jLabelSum.setText("0");
        NumbersPanel.add(jLabelSum);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Overall Total Records:   ");
        NumbersPanel.add(jLabel6);

        jLabelTotalInventory.setText("0");
        NumbersPanel.add(jLabelTotalInventory);

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NumbersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(NumbersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        getContentPane().add(BottomPanel, java.awt.BorderLayout.PAGE_END);
        BottomPanel.getAccessibleContext().setAccessibleName("BottomPanel");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        System.out.println("add");
        JDialog dialog = new AddDialogue(this, true, db, tblModel);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        System.out.println("update");
        if (InventoryTable.getSelectedRow() == -1) {
            showNoRecordsDialogue();
        } else {
            JDialog dialog = new UpdateDialogue(this, true, db, tblModel, tblModel.getValueAt(InventoryTable.getSelectedRow(), 0).toString(), InventoryTable);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed


    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (InventoryTable.getSelectedRow() == -1) {
            showNoRecordsDialogue();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Are you sure to delete " + tblModel.getValueAt(InventoryTable.getSelectedRow(), 1).toString(), "DELETE",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                db.deleteRow(tblModel.getValueAt(InventoryTable.getSelectedRow(), 0).toString());
                tblModel.removeRow(InventoryTable.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String query = jTextField1.getText();
        filter(query);
        if(query.equals("")){
            state = true;
        }
        else{
            state = false;
        }
        disableButton();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void showNoRecordsDialogue() {
        JOptionPane.showMessageDialog(this, "No record selected", "Warning",
                JOptionPane.WARNING_MESSAGE);
    }

    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tblModel);
        InventoryTable.setRowSorter(tr);      
        tr.setRowFilter(RowFilter.regexFilter(query));
       
    }

    private void setSum() {
        jLabelSum.setText(db.getTotalInventorySum());
        jLabelTotalInventory.setText(Integer.toString(db.getRowCount()));
                InventoryTable.getModel().addTableModelListener(new TableModelListener() {
            public void tableChanged(TableModelEvent e) {   
                setSum();
            }
        });
    }
    boolean state;
    private void disableButton(){        
        jButtonAdd.setEnabled(state);
        jButtonUpdate.setEnabled(state);
        jButtonDelete.setEnabled(state);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JLabel IconLabel;
    public javax.swing.JTable InventoryTable;
    private javax.swing.JPanel NumbersPanel;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelSum;
    private javax.swing.JLabel jLabelTotalInventory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
